name: Maven CI Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Maven Build
    runs-on: namespace-profile-with-caching
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"

      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@main
        # with:
        #   token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Build with Maven
        run: ./mvnw verify

      - name: Breakpoint on failure
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 15m
          authorized-users: n-g
